sudo: required
services:
  - docker

before_install:
  - docker build -t gp04/react-test -f ./client/Dockerfile.dev ./client
    
script:
  - docker run gp04/react-test npm test -- --coverage

after_success:
  - docker build -t gp04/multi-client ./client
  - docker build -t gp04/multi-nginx ./nginx
  - docker build -t gp04/multi-server ./server
  - docker build -t gp04/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the images and push them to Docker Hub
  - docker push gp04/multi-client
  - docker push gp04/multi-nginx 
  - docker push gp04/multi-server
  - docker push gp04/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-110317745535
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY